In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [9]:
demo_fruitnut = pd.read_csv('../data/fruittreenuttotals_demographics.csv')
demo_berries = pd.read_csv('../data/demographics_berries.csv')
demo_citrus = pd.read_csv('../data/demographics_citrus.csv')
demo_vegetables = pd.read_csv('../data/demographics_vegetables.csv')

In [33]:
berry_org_types = demo_berries.loc[(demo_berries['Domain'] == 'ORGANIZATION') & (demo_berries['Data Item'] == 'BERRY TOTALS - OPERATIONS WITH SALES')]
berry_org_types

,Program,Year,Period,Week Ending,Geo Level,State,State ANSI,Ag District,Ag District Code,County,...,Zip Code,Region,watershed_code,Watershed,Commodity,Data Item,Domain,Domain Category,Value,CV (%)
32,CENSUS,2022,YEAR,NaN,NATIONAL,US TOTAL,NaN,NaN,NaN,NaN,...,NaN,NaN,0,NaN,BERRY TOTALS,BERRY TOTALS - OPERATIONS WITH SALES,ORGANIZATION,"ORGANIZATION: (TAX PURPOSES, CORPORATION)","3,977",5.7
33,CENSUS,2022,YEAR,NaN,NATIONAL,US TOTAL,NaN,NaN,NaN,NaN,...,NaN,NaN,0,NaN,BERRY TOTALS,BERRY TOTALS - OPERATIONS WITH SALES,ORGANIZATION,"ORGANIZATION: (TAX PURPOSES, CORPORATION, (EXC...",661,6.5
34,CENSUS,2022,YEAR,NaN,NATIONAL,US TOTAL,NaN,NaN,NaN,NaN,...,NaN,NaN,0,NaN,BERRY TOTALS,BERRY TOTALS - OPERATIONS WITH SALES,ORGANIZATION,"ORGANIZATION: (TAX PURPOSES, CORPORATION, (EXC...",633,6.7
35,CENSUS,2022,YEAR,NaN,NATIONAL,US TOTAL,NaN,NaN,NaN,NaN,...,NaN,NaN,0,NaN,BERRY TOTALS,BERRY TOTALS - OPERATIONS WITH SALES,ORGANIZATION,"ORGANIZATION: (TAX PURPOSES, CORPORATION, FAMI...","3,316",6.0
36,CENSUS,2022,YEAR,NaN,NATIONAL,US TOTAL,NaN,NaN,NaN,NaN,...,NaN,NaN,0,NaN,BERRY TOTALS,BERRY TOTALS - OPERATIONS WITH SALES,ORGANIZATION,"ORGANIZATION: (TAX PURPOSES, CORPORATION, FAMI...","3,252",6.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18728,CENSUS,2012,YEAR,NaN,STATE,WISCONSIN,55.0,NaN,NaN,NaN,...,NaN,NaN,0,NaN,BERRY TOTALS,BERRY TOTALS - OPERATIONS WITH SALES,ORGANIZATION,"ORGANIZATION: (TAX PURPOSES, PARTNERSHIP, REGI...",70,8.0
18891,CENSUS,2012,YEAR,NaN,STATE,WYOMING,56.0,NaN,NaN,NaN,...,NaN,NaN,0,NaN,BERRY TOTALS,BERRY TOTALS - OPERATIONS WITH SALES,ORGANIZATION,"ORGANIZATION: (TAX PURPOSES, CORPORATION)",2,94.9
18892,CENSUS,2012,YEAR,NaN,STATE,WYOMING,56.0,NaN,NaN,NaN,...,NaN,NaN,0,NaN,BERRY TOTALS,BERRY TOTALS - OPERATIONS WITH SALES,ORGANIZATION,"ORGANIZATION: (TAX PURPOSES, CORPORATION, FAMI...",2,94.9
18893,CENSUS,2012,YEAR,NaN,STATE,WYOMING,56.0,NaN,NaN,NaN,...,NaN,NaN,0,NaN,BERRY TOTALS,BERRY TOTALS - OPERATIONS WITH SALES,ORGANIZATION,"ORGANIZATION: (TAX PURPOSES, CORPORATION, FAMI...",2,94.9
18894,CENSUS,2012,YEAR,NaN,STATE,WYOMING,56.0,NaN,NaN,NaN,...,NaN,NaN,0,NaN,BERRY TOTALS,BERRY TOTALS - OPERATIONS WITH SALES,ORGANIZATION,"ORGANIZATION: (TAX PURPOSES, FAMILY & INDIVIDUAL)",6,61.2

In [29]:
berry_org_types.to_csv(path_or_buf = 'berry_org_types.csv', index = False)

In [47]:
veg_org_types = demo_vegetables.loc[(demo_vegetables['Domain'] == 'ORGANIZATION') & (demo_vegetables['Data Item'] == 'VEGETABLE TOTALS, INCL SEEDS & TRANSPLANTS, IN THE OPEN - OPERATIONS WITH SALES')]
veg_org_types.to_csv(path_or_buf = 'veg_org_types.csv', index = False)

In [53]:
demo_vegetables['Domain Category'].loc[(demo_vegetables['Domain'] == 'ORGANIZATION')].unique()

array(['ORGANIZATION: (TAX PURPOSES, CORPORATION)',
       'ORGANIZATION: (TAX PURPOSES, CORPORATION, (EXCL FAMILY HELD))',
       'ORGANIZATION: (TAX PURPOSES, CORPORATION, (EXCL FAMILY HELD), LE 10 STOCKHOLDERS)',
       'ORGANIZATION: (TAX PURPOSES, CORPORATION, FAMILY HELD)',
       'ORGANIZATION: (TAX PURPOSES, CORPORATION, FAMILY HELD, LE 10 STOCKHOLDERS)',
       'ORGANIZATION: (TAX PURPOSES, FAMILY & INDIVIDUAL)',
       'ORGANIZATION: (TAX PURPOSES, INSTITUTIONAL & RESEARCH & RESERVATION & OTHER)',
       'ORGANIZATION: (TAX PURPOSES, PARTNERSHIP)',
       'ORGANIZATION: (TAX PURPOSES, PARTNERSHIP, REGISTERED UNDER STATE LAW)'],
      dtype=object)